### PR TITLE
fix(geojson-point): handle required attribute on lat and lng inputs

### LINKED ISSUE #38: Handle required latitude and longitude for geoJson point
especially for quiz we could need that latitude and longitude are set to required

### PR DESCRIPTION
**Pull request by benib**
This fixes #38

### CODE REVIEW

File: client/src/elements/schema-editor/schema-editor-geojson-point.js [hunk 1]
```diff
@@ -36,6 +38,7 @@ export class SchemaEditorGeojsonPoint {
     this.applyOptions();
     await this.handleOptions();
     await this.updateBbox();
+    console.log(this.schema);
```
Comment (fuenkchen) [inline client/src/elements/schema-editor/schema-editor-geojson-point.js]: remove this?
