### PR TITLE
load fonts in livingsdocs preview

### LINKED ISSUE #216: livingdocs-component should load stylesheets from editor config
### livingdocs-component should load stylesheets from editor config

Because it's not possible to load fonts in a shadow-root we need to load any fonts needed to correctly display the preview outside of the shadow-root.
This is currently done within app.js here: https://github.com/nzzdev/Q-editor/blob/dev/client/src/app.js#L94-L123
This code injects any stylesheets defined in editor config sent by Q-server in the `stylesheets` property.

We have a separate Aurelia app in livingdocs-component-app/app.html used for the Q Livingdocs Component. It contains a preview as well. This is done because we do not want to load the complete Q Editor app for this component.

Currently we do not load the stylesheets with the fonts in this app. This results in the fonts not being displayed correctly in the preview.

### Steps to Reproduce

1. Open Livingdocs Component at your-q-editor-url.ch/livingdocs-component.html
2. Select a graphic
3. inspect an element with a font and see that it is not rendered with the correct font

**Expected behavior:** The font files should be loaded and text should be rendered with the correct font

**Reproduces how often:** always

### PR DESCRIPTION
**Pull request by philipkueng**
Closes #216

### CODE REVIEW

File: client/src/livingdocs-component-app/app.js [hunk 1]
```diff
@@ -46,6 +50,36 @@ export class App {
     if (this.selectedItem) {
       await this.loadPreview();
     }
+
+    // load any additional stylesheets defined for themeing or font-face loading as @font-face doesn't work within ShadowRoot (used for the preview)
+    try {
```
Comment (benib) [inline client/src/livingdocs-component-app/app.js]: Imo the stylesheets should be loaded before the preview is loaded (or at least at the same time), otherwise there could be a flash of font change. maybe extract the stylesheet loading in a separate function and call it at the beginning of `attached` without await, so the stylesheets get loaded parallel to the preview?

File: client/src/livingdocs-component-app/app.js [hunk 2]
```diff
@@ -199,7 +204,7 @@ export class App {
     if (!this.selectedItem.toolRuntimeConfig.displayOptions) {
       this.selectedItem.toolRuntimeConfig.displayOptions = await this.getDefaultDisplayOptions();
     }
-
+    debugger;
```
Comment (benib) [inline client/src/livingdocs-component-app/app.js]: please remove these debugger statements...
